name: Mirror Repo
on:
  schedule:
    # nightly (0th hour 0th minute of every day)
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Mirror
      run: |
        mkdir ~/.ssh
        touch ~/.shh/known_hosts
        ssh-keyscan -t rsa sovietlinux.ml >> ~/.ssh/known_hosts
        git https://git.sovietlinux.ml/sovietlinux/CCCP.git
        git -C CCCP push https://github.com/Soviet-Linux/CCCP
