name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure spm
      run: git clone https://github.com/Soviet-Linux/libspm && cd libspm && sudo mkdir -p /usr/include/spm/ && cp include/*.h /usr/include/spm/ 
    - name: make
      run: make
    - name: make clean
      run: make clean