name: Mirror Repo
on:
  schedule:
    # nightly (0th hour 0th minute of every day)
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Mirror
      run: |
        ssh-keyscan -t rsa sovietlinux.ml >> ~/.ssh/known_hosts
        git clone git@sovietlinux.ml:/srv/git/dev/CCCP
        cd CCCP/
        git remote add github https://github.com/Soviet-Linux/CCCP
        git push github

