name: Mirror Repo
on:
  schedule:
    # nightly (0th hour 0th minute of every day)
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Mirror
      run: |
      gt clone git@sovietlinux.ml:/srv/git/dev/CCCP
        cd CCCP/
        git remote add github https://github.com/Soviet-Linux/CCCP
        git push github
      env:
        GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
